RANDOM_SEED = 42

# Data split
VALIDATION_SIZE = 0.2

# TF-IDF settings
TFIDF_MAX_FEATURES = 10000
TFIDF_STOP_WORDS = "english"
TFIDF_MIN_DF = 2
TFIDF_MAX_DF = 0.95
TFIDF_NGRAM_RANGE = (1, 1)

# MLP settings
MLP_HIDDEN_DIM = 128
MLP_LEARNING_RATE = 1e-3
MLP_EPOCHS = 10
MLP_BATCH_SIZE = 64

# Word2Vec settings
W2V_VECTOR_SIZE = 100
W2V_WINDOW = 5
W2V_MIN_COUNT = 2
W2V_WORKERS = 4
W2V_EPOCHS_SHORT = 1
W2V_EPOCHS_LONG = 10
W2V_SG = 1  # 1 = Skip-gram, 0 = CBOW

# BERT settings
BERT_MODEL_NAME = "bert-base-uncased"
BERT_MAX_LENGTH = 64
BERT_BATCH_SIZE = 8
BERT_LEARNING_RATE = 2e-5
BERT_EPOCHS = 2
BERT_WEIGHT_DECAY = 0.01